# Generated by Django 5.2 on 2025-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator_backend', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
