# Generated by Django 5.2 on 2025-04-29 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator_backend', '0003_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(max_length=50, unique=True, verbose_name='Project ID')),
                ('team_leader_name', models.CharField(max_length=255, verbose_name='Team Leader Full Name')),
                ('team_leader_year', models.CharField(max_length=50, verbose_name='Team Leader Year of Study')),
                ('team_leader_email', models.EmailField(max_length=254, verbose_name='Team Leader Email Address')),
                ('team_leader_phone', models.CharField(max_length=20, verbose_name='Team Leader Phone Number')),
                ('team_members', models.TextField(verbose_name='Team Members')),
                ('project_title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('project_domain', models.CharField(blank=True, max_length=100, verbose_name='Project Domain')),
                ('is_ai_project', models.BooleanField(default=False, verbose_name='Is AI Project')),
                ('project_summary', models.TextField(verbose_name='Project Summary')),
                ('dev_stage', models.CharField(choices=[('idea', 'Idea Stage'), ('prototype', 'Prototype'), ('mvp', 'Minimum Viable Product'), ('scaling', 'Scaling')], default='idea', max_length=50, verbose_name='Development Stage')),
                ('demo_link', models.URLField(verbose_name='Demo/Working Application Link')),
                ('project_video', models.URLField(blank=True, verbose_name='Project Video')),
                ('key_milestones', models.TextField(verbose_name='Key Milestones Achieved')),
                ('current_challenges', models.TextField(verbose_name='Current Challenges')),
                ('problem_statement', models.TextField(verbose_name='Problem Statement')),
                ('target_audience', models.TextField(blank=True, verbose_name='Target Audience')),
                ('expected_impact', models.TextField(verbose_name='Expected Impact')),
                ('additional_motivation', models.TextField(blank=True, verbose_name='Additional Motivation')),
                ('supporting_documents', models.FileField(blank=True, upload_to='incubation_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip'])], verbose_name='Supporting Documents')),
                ('confirmation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incubation Form',
                'verbose_name_plural': 'Incubation Forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
