# Generated by Django 5.2 on 2025-05-02 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incubator_backend", "0002_add_roles"),
        ("incubator_backend", "0004_incubationform"),
    ]

    operations = []
