# Generated by Django 5.2 on 2025-05-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator_backend', '0005_merge_0002_add_roles_0004_incubationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incubator_backend.stage'),
        ),
        migrations.AlterModelTable(
            name='incubationform',
            table='incubator_backend_incubation_form',
        ),
    ]
