# Generated by Django 5.2 on 2025-05-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator_backend', '0006_startup_stage_alter_incubationform_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationFormScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_understanding', models.IntegerField(default=0)),
                ('solution_fit', models.IntegerField(default=0)),
                ('technical_soundness', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incubation_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incubator_backend.incubationform')),
            ],
            options={
                'db_table': 'incubator_backend_incubation_form_score',
            },
        ),
    ]
