# Generated by Django 5.2 on 2025-05-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator_backend', '0007_incubationformscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubationformscore',
            name='incubation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='incubator_backend.incubationform'),
        ),
    ]
